sudo: required
language: node_js
node_js:
  - "8"
install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install awscli
  - npm install
script:
  - npm run build
  - mkdir dist-zip
  - cp package.json dist/
  - cp package-lock.json dist/
  - zip -r dist-zip/$TRAVIS_COMMIT.zip dist
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: psycollect-api
  skip_cleanup: true
  local_dir: dist-zip
after_deploy:
  - aws elasticbeanstalk create-application-version --application-name psycollect-api --version-label $TRAVIS_COMMIT --source-bundle S3Bucket=psycollect-api,S3Key=$TRAVIS_COMMIT.zip --region=us-east-1
  - aws elasticbeanstalk update-environment --application-name psycollect-api --environment-name psycollect-api --version-label $TRAVIS_COMMIT --region=us-east-1
